### ISSUE TITLE
Browserify incompatibility

### ISSUE THREAD

**Issue by ghost** [Kikobeats/cb2promise#2]
I encounter errors related to this module when trying to user browserify:
```
03 02 2017 13:12:28.521:ERROR [framework.browserify]: bundle error
03 02 2017 13:12:28.521:ERROR [framework.browserify]: Error: Cannot find module './lib/cb2promise' 
```

This is due to the `require` call in `index.js`.
Can I submit a pull request prefixing the path with `__dirname`?

**Comment by Kikobeats** [comment]
sure!
