### ISSUE TITLE
Issue building with webpack

### ISSUE THREAD

**Issue by johnryan** [Kikobeats/cb2promise#4]
After adding this dependency i'm seeing an error:

```
ERROR in ./~/cb2promise/index.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/johnryan/Desktop/app/node_modules/cb2promise/lib/cb2promise in /Users/johnryan/Desktop/app/node_modules/cb2promise
 @ ./~/cb2promise/index.js 3:17-55
```

and

```
ERROR in ./~/coffee-script/bin/coffee
Module parse failed: /Users/johnryan/Desktop/app/node_modules/coffee-script/bin/coffee Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected character '#' (1:0)
```

Is there a recommended solution for this?

**Comment by Kikobeats** [comment]
I suppose is buggy here: https://github.com/Kikobeats/cb2promise/blob/master/index.js#L3

line for added browserify compatebility.

path need to be resolved usings `path`, like: 

```js
const libpath = path.resolve('lib/cb2promise')
module.exports = require(libpath)
```

can you try this modification and send me feedback?

**Comment by johnryan** [comment]
@Kikobeats changing index.js to: 

```
'use strict';
require('coffee-script/register');
const libpath = path.resolve('lib/cb2promise')
module.exports = require(libpath)
```
had no effect...it appears to be some issue parsing the coffeescript with webpack

**Comment by Kikobeats** [comment]
looks like you need to load cofeescript previously on webpack

**Comment by dok** [comment]
The error still occurs even if you load coffeescript onto webpack... Can we change the "main" in package.json to point to dist/cb2promise.js?
